#list files in the workign directory
my_rib_files<-list.files()
setwd("C:/Users/V_ONANA/Documents/Ribosomal_proteins/Ribo_Prot_S1_L2/")

#Read in folder into R environment 
rm(temp)
my_rib_pro_files <- list.files(pattern = "*.unifrac")
                       
##Read files into global environment with list.env
list2env(
  lapply(setNames(my_rib_pro_files, make.names(gsub(".unifrac$", "", my_rib_pro_files))),
  read.delim, header=F), envir = .GlobalEnv)
?make.names
#head of files 
tail(X06.071_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)
test<-as.data.frame(my_rib_pro_files)

colnames(X06.080_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.095_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.102_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.104_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.126_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.127_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.129_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.131_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.132_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.136_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.140_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.141_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.142_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.156_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.161_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.167_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.174_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.196_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.198_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.199_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.217_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X06.220_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.001_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.002_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.003_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.006_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.007_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.008_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.009_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.010_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.011_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.014_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.015_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.021_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.022_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.026_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.028_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.029_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.030_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.031_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.032_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.033_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.040_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.047_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.049_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.051_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.055_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X07.057_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.097_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.120_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.134_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.135_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.138_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.144_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.152_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.155_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.157_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.160_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.164_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.168_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.179_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.180_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.183_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.184_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.186_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.188_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.189_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.193_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.194_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.197_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.210_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.212_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.216_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X08.219_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.018_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.027_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.043_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.050_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.054_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.056_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.058_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.060_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.061_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.063_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.065_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.067_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.072_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.073_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.074_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.077_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.086_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.090_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.091_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.093_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.098_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.107_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.112_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.113_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")
colnames(X17.116_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB)<-c("Seq","Lake_ID","RP_Abund")

#get all dataframes to merge


DF_env <- lapply(ls(), get)
DF_all<-lapply(ls(), get)

mergefun <- function(x, y) merge(x, y, by= "Seq")

merged_DF <- Reduce(mergefun, DF_env)
merge.1<-merge(X06.071_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB,X06.080_R1.fastq.gz_otu_table.csv.unifrac.otu.S1.1.ribosomal_protein_L2_rplB, by="Seq",all.x = T, all.y = T)

##########
datalist <- mget(ls(pattern = "*.ribosomal_protein_L2_rplB"))
Trial<-Reduce(function(x, y) merge(x=x, y=y, by="Seq", all.x=T, all.y=T), datalist)
head(Trial)
############
#####use purr and tidyverse
library(tidyverse)
library(purrr)
#Trial.2<-datalist %>% doesnt work
  map_df(gather, key=key, value=value, -"Seq") %>% 
  spread(key, value)
####Use reshape 
library(reshape)
Trial.3<-merge_all(datalist)  
install.packages("reshape")  
?merge_all
####aggregate dataframe by lake ID
Test_agg<-aggregate(.~Lake_ID,Trial.3,toString)
unfactor.lake<-unfactor(Trial.3$Lake_ID)
library(varhandle)          
Test_agg<-aggregate(.~Seq,Trial.3,toString)
